### ISSUE TITLE
ClassNotFoundException when trying to run liquibase update

### ISSUE THREAD

**Issue by ogrian** [liquibase/liquibase-couchbase#43]
Hi!

I'm trying to run liquibase-couchbase from command line. I've put the last release of the extension into the liquibase lib folder and configured liquibase.properties etc.
However, when I'm running liquibase, I get the following exception:

```
Unexpected error running Liquibase: com/couchbase/client/core/util/ConnectionString
  - Caused by: com.couchbase.client.core.util.ConnectionString

java.lang.NoClassDefFoundError: com/couchbase/client/core/util/ConnectionString
        at liquibase.ext.couchbase.database.CouchbaseConnection.open(CouchbaseConnection.java:172)
        at liquibase.database.ConnectionServiceFactory.create(ConnectionServiceFactory.java:32)
        at liquibase.database.DatabaseFactory.openConnection(DatabaseFactory.java:218)
        at liquibase.database.DatabaseFactory.openConnection(DatabaseFactory.java:179)
        at liquibase.database.DatabaseFactory.openDatabase(DatabaseFactory.java:144)
        at liquibase.command.core.helpers.AbstractDatabaseConnectionCommandStep.createDatabaseObject(AbstractDatabaseConnectionCommandStep.java:75)
        at liquibase.command.core.helpers.DbUrlConnectionCommandStep.obtainDatabase(DbUrlConnectionCommandStep.java:92)
        at liquibase.command.core.helpers.DbUrlConnectionCommandStep.run(DbUrlConnectionCommandStep.java:69)
        at liquibase.command.CommandScope.execute(CommandScope.java:213)
        at liquibase.integration.commandline.CommandRunner.call(CommandRunner.java:55)
        at liquibase.integration.commandline.CommandRunner.call(CommandRunner.java:24)
        at picocli.CommandLine.executeUserObject(CommandLine.java:2041)
        at picocli.CommandLine.access$1500(CommandLine.java:148)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
        at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
        at picocli.CommandLine.execute(CommandLine.java:2170)
        at liquibase.integration.commandline.LiquibaseCommandLine.lambda$execute$2(LiquibaseCommandLine.java:382)
        at liquibase.Scope.child(Scope.java:206)
        at liquibase.Scope.child(Scope.java:182)
        at liquibase.integration.commandline.LiquibaseCommandLine.lambda$execute$3(LiquibaseCommandLine.java:357)
        at liquibase.Scope.child(Scope.java:206)
        at liquibase.Scope.child(Scope.java:182)
        at liquibase.integration.commandline.LiquibaseCommandLine.execute(LiquibaseCommandLine.java:355)
        at liquibase.integration.commandline.LiquibaseCommandLine.main(LiquibaseCommandLine.java:95)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.base/java.lang.reflect.Method.invoke(Unknown Source)
        at liquibase.integration.commandline.LiquibaseLauncher.main(LiquibaseLauncher.java:107)
Caused by: java.lang.ClassNotFoundException: com.couchbase.client.core.util.ConnectionString
        at java.base/java.net.URLClassLoader.findClass(Unknown Source)
        at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
        at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
        ... 32 more
```

Looks like some library is missing. Is it expected to have Couchbase java-client library on the classpath or is the case more complicated than I think?

Thank you in advance.

**Comment by ogrian** [comment]
Yes, it was missing some jars. I've added them to the lib folder.

**Comment by ogrian** [comment]
The list of the jar I had to add:

core.io (Couchbase)
java-client (Couchbase)
json-schema-validator
jackson-core
jackson-annotations
jackson-databind
jackson-dataformat-yaml
reactive-streams
reactor-core
slf4j-api

**Comment by romchellis** [comment]
Hi @ogrian ,
so can we close issue?

**Comment by ogrian** [comment]
> Hi @ogrian , so can we close issue?

Yes, sure, thank you!

**Comment by DaimonCool** [comment]
Hi @ogrian 

Thank you for your information. We updated the README documentation and added the list of jars we need to add to run CLI.
